# Generated by Django 3.2.9 on 2021-11-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.beer')),
            ],
        ),
    ]
